"use client"
import './globals.css'
import { Inter } from 'next/font/google';
// import { Providers } from '../redux/Providers';
import { ThemeProvider } from 'next-themes';
import { Navbar } from '@/components';
import Image from 'next/image'
import { facebookLogo, instagramLogo, githubLogo } from '@/assets/images';


const inter = Inter({ subsets: ['latin'] });

const metadata = {
  title: 'Loi Phan',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* <Providers> */}
        <ThemeProvider enableSystem={true} attribute="class">
          <div
            className="dark:bg-dark-bg dark:text-dark-text"
          >
            <div
              className="md:mx-auto max-w-[1160px] min-h-screen w-[100%]  md:py-[48px]
              px-[16px] md:px-[30px] box-border 2xl:px-[32px] "
            >
              <Navbar></Navbar>

              <section
                className="w-auto min-h-[75vh]"
              >
                {children}
              </section>

              <footer
                className="flex w-[100%] py-[48px] md:py-0 box-border h-fit flex-col justify-center items-center"
              >
                <ul
                  className="flex flex-row gap-3"
                >
                  <li
                    className="flex flex-row items-center gap-2"
                  >
                    <p>
                      GitHub
                    </p>

                    <Image
                      src={githubLogo}
                      alt='GitHub'
                    />
                  </li>
                  <li
                    className="flex flex-row items-center gap-2"
                  >
                    <p>
                      Instagram
                    </p>

                    <Image
                      src={instagramLogo}
                      alt='Instagram'
                    />
                  </li>
                  <li
                    className="flex flex-row items-center gap-2"
                  >
                    <p>
                      Facebook
                    </p>

                    <Image
                      src={facebookLogo}
                      alt='Facebook'
                    />
                  </li>
                </ul>
                <p className="mt-[20px]">Made by Loi Phan.</p>
              </footer>
            </div>
          </div>
        </ThemeProvider>
        {/* </Providers> */}
      </body>
    </html>
  )
}

export default RootLayout;